<?php

/**
 * This file is based on a translation of the pref_voting python package
 * (https://github.com/voting-tools/pref_voting/)
 * Copyright (c) 2024 Wes Holliday and Eric Pacuit, MIT licensed.
 *
 * This file Copyright (c) 2026 Dominik Peters, also MIT licensed.
 */

declare(strict_types=1);

namespace PrefVoting;

/**
 * A mapping of grades to candidates.
 */
class Grade extends Mapping
{
    /** @var array<int|string> The allowed grades */
    public array $grades;

    /** @var array<int|string> The candidates */
    public array $candidates;

    /** @var array<int|string, string> Candidate display names */
    public array $cmap;

    /** @var array<mixed, string> Grade display names */
    public array $gmap;

    /**
     * @param array<int|string, mixed> $gradeMap Map from candidate to grade
     * @param array<mixed> $grades The allowed grades
     * @param array<int|string>|null $candidates The candidates
     * @param array<int|string, string>|null $cmap Candidate display names
     * @param array<mixed, string>|null $gmap Grade display names
     * @param callable|null $compareFunction Function to compare grades
     */
    public function __construct(
        array $gradeMap,
        array $grades,
        ?array $candidates = null,
        ?array $cmap = null,
        ?array $gmap = null,
        ?callable $compareFunction = null
    ) {
        $this->grades = $grades;
        foreach ($gradeMap as $g) {
            if (!in_array($g, $grades, true)) {
                throw new \InvalidArgumentException("All grades in the grade map must be in the allowed grades.");
            }
        }

        $this->candidates = $candidates ?? array_keys($gradeMap);
        sort($this->candidates);

        foreach (array_keys($gradeMap) as $x) {
            if (!in_array($x, $this->candidates, true)) {
                throw new \InvalidArgumentException("The candidates list must contain all elements in the grade map.");
            }
        }

        $this->cmap = $cmap ?? array_combine($this->candidates, array_map('strval', $this->candidates));
        $this->gmap = $gmap ?? array_combine($this->grades, array_map('strval', $this->grades));

        parent::__construct($gradeMap, $this->candidates, $this->grades, $compareFunction, $this->cmap, $this->gmap);
    }

    /**
     * Returns a list of the items that are assigned a grade.
     */
    public function gradedCandidates(): array
    {
        return $this->definedDomain();
    }

    /**
     * Returns a list of the items that are assigned the grade g.
     */
    public function candidatesWithGrade(mixed $g): array
    {
        return $this->inverseImage($g);
    }

    /**
     * Return True if x has a grade.
     */
    public function hasGrade(int|string $x): bool
    {
        return $this->hasValue($x);
    }

    /**
     * Returns a grade function with the item x removed.
     */
    public function removeCand(int|string $x): Grade
    {
        $newGrades = [];
        foreach ($this->definedDomain() as $y) {
            if ($y !== $x) $newGrades[$y] = $this->val($y);
        }
        $newCandidates = array_values(array_filter($this->candidates, fn($y) => $y !== $x));
        $newCmap = [];
        foreach ($this->cmap as $y => $name) {
            if ($y !== $x) $newCmap[$y] = $name;
        }
        return new Grade($newGrades, $this->grades, $newCandidates, $newCmap, $this->gmap, $this->compareFunction);
    }

    /**
     * Return the ranking generated by this grade function.
     */
    public function ranking(): Ranking
    {
        $rmap = [];
        $sortedDomain = $this->sortedDomain();
        foreach ($sortedDomain as $idx => $indiffClass) {
            foreach ($indiffClass as $x) {
                $rmap[$x] = $idx + 1;
            }
        }
        return new Ranking($rmap, $this->cmap);
    }

    /**
     * Return the ranking generated by this grade function (extended).
     */
    public function extendedRanking(): Ranking
    {
        $rmap = [];
        $sortedDomain = $this->sortedDomain(true);
        foreach ($sortedDomain as $idx => $indiffClass) {
            foreach ($indiffClass as $x) {
                $rmap[$x] = $idx + 1;
            }
        }
        return new Ranking($rmap, $this->cmap);
    }

    /**
     * Return True when the utility has a tie.
     */
    public function hasTie(bool $useExtended = false): bool
    {
        foreach ($this->sortedDomain($useExtended) as $cs) {
            if (count($cs) !== 1) return true;
        }
        return false;
    }

    /**
     * Return True when the assignment of grades is a linear order of numCands candidates.
     */
    public function isLinear(int $numCands): bool
    {
        return $this->ranking()->isLinear($numCands);
    }

    public function __toString(): string
    {
        $parts = [];
        foreach ($this->domain as $x) {
            $val = $this->val($x);
            $valStr = $val === null ? "None" : ($this->gmap[$val] ?? (string)$val);
            $parts[] = "grade({$this->cmap[$x]}) = $valStr";
        }
        return implode(", ", $parts);
    }
}
