<?php

namespace App\Services\Reports;

use App\Models\Question;
use App\Services\ProfileBuilder;
use App\Services\SocialWelfareFunctionRegistry;

class MultiSWFComparisonReport extends BaseReport
{
    public function getType(): string
    {
        return 'multi_swf_comparison';
    }

    public function getName(): string
    {
        return 'Rank Aggregation Rule Comparison';
    }

    public function getDescription(): string
    {
        return 'Compares rankings generated by multiple Rank Aggregation Rules';
    }

    public function getSupportedQuestionTypes(): array
    {
        return ['ranking'];
    }

    public function getIcon(): string
    {
        return 'columns';
    }

    public function getConfigSchema(): ?array
    {
        return [
            'fields' => [
                [
                    'name' => 'swfs',
                    'type' => 'checkboxes',
                    'label' => 'Rank Aggregation Rules to Compare',
                    'required' => true,
                    'options' => [], // Populated dynamically
                    'dynamicOptions' => 'socialWelfareFunctions',
                ],
            ],
        ];
    }

    public function compute(Question $question, array $responses, ?array $config): array
    {
        $selectedSWFs = $config['swfs'] ?? SocialWelfareFunctionRegistry::getDefaultSWFs($question->type);
        $labels = ProfileBuilder::getOptionLabels($question);
        $allSWFs = SocialWelfareFunctionRegistry::getSWFsForQuestionType($question->type);

        $profile = ProfileBuilder::fromRankingResponses($question, $responses);

        $question->loadOptions();
        $indexToOptionId = [];
        foreach ($question->options as $index => $option) {
            $indexToOptionId[$index] = $option->id;
        }

        $results = [];
        foreach ($selectedSWFs as $swfKey) {
            if (!isset($allSWFs[$swfKey])) {
                continue;
            }

            $swfFactory = SocialWelfareFunctionRegistry::getMethod($swfKey, $question->type);
            if ($swfFactory === null) {
                continue;
            }

            $rankingObjects = $swfFactory($profile);
            $rankings = [];
            foreach ($rankingObjects as $rankingObj) {
                $indiffList = $rankingObj->toIndiffList();
                $formattedRanking = [];
                foreach ($indiffList as $tier) {
                    $formattedTier = [];
                    foreach ($tier as $idx) {
                        $optionId = $indexToOptionId[$idx] ?? $idx;
                        $formattedTier[] = [
                            'option_id' => $optionId,
                            'option' => $labels[$optionId] ?? $rankingObj->cmap[$idx] ?? "Option {$idx}",
                        ];
                    }
                    $formattedRanking[] = $formattedTier;
                }
                $rankings[] = $formattedRanking;
            }

            $results[] = [
                'swf' => $swfKey,
                'swf_name' => $allSWFs[$swfKey]['name'],
                'rankings' => $rankings,
                'is_tie' => count($rankings) > 1,
            ];
        }

        return [
            'results' => $results,
            'total_swfs' => count($results),
            'total_responses' => count($responses),
        ];
    }
}
